Fix NoMethodError: undefined method `Equalizer' for Dry:Module`
For example
if require "dry/monads/either" in dry-transaction

See travis build
https://travis-ci.org/dry-rb/dry-transaction/jobs/154516191#L223